apiVersion: v1
kind: Pod
metadata:
  name: oom-killed-fixed-pod
spec:
  containers:
  - name: stress
    image: polinux/stress
    resources:
      limits:
        memory: "256Mi"
      requests:
        memory: "128Mi"
    command: ["stress", "--vm", "1", "--vm-bytes", "50M"]
