apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler-fixed-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
