apiVersion: v1
kind: Pod
metadata:
  name: failed-resource-limits-fixed-pod
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress", "--vm", "1", "--vm-bytes", "50M"]
    resources:
      limits:
        memory: "256Mi"
