apiVersion: v1
kind: Pod
metadata:
  name: disk-io-error-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "ls /data && sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    emptyDir: {}
