apiVersion: v1
kind: Pod
metadata:
  name: network-connectivity-issue-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "wget -qO- --timeout=5 http://google.com; sleep 3600"]
