apiVersion: v1
kind: Pod
metadata:
  name: crash-disk-space-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "dd if=/dev/zero of=/tmp/fill bs=1M count=10; sleep 3600"]
    resources:
      limits:
        ephemeral-storage: "5Mi"
